<?php
namespace incl;

/**
 * @package mod\solid_classes
 * @author Ryno Van Zyl
 */

class library extends \Kwerqy\Ember\com\intf\standard {

	public static $index_arr = [
				"ERROR_CODE_LOGIN_INVALID" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_1",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_1.php",
			"constant" => "ERROR_CODE_LOGIN_INVALID",
			"value" => "1",
			"category" => "ERROR",
		],
		"ERROR_CODE_ACCESS_DENIED" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_10",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_10.php",
			"constant" => "ERROR_CODE_ACCESS_DENIED",
			"value" => "10",
			"category" => "ERROR",
		],
		"ERROR_CODE_ACCOUNT_LOCKED" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_11",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_11.php",
			"constant" => "ERROR_CODE_ACCOUNT_LOCKED",
			"value" => "11",
			"category" => "ERROR",
		],
		"ERROR_CODE_CAPTCHA_ERROR" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_12",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_12.php",
			"constant" => "ERROR_CODE_CAPTCHA_ERROR",
			"value" => "12",
			"category" => "ERROR",
		],
		"ERROR_CODE_SYSTEM_OFFLINE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_13",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_13.php",
			"constant" => "ERROR_CODE_SYSTEM_OFFLINE",
			"value" => "13",
			"category" => "ERROR",
		],
		"ERROR_CODE_ACCOUNT_INACTIVE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_14",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_14.php",
			"constant" => "ERROR_CODE_ACCOUNT_INACTIVE",
			"value" => "14",
			"category" => "ERROR",
		],
		"ERROR_CODE_CSRF_TOKEN_MISSING" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_15",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_15.php",
			"constant" => "ERROR_CODE_CSRF_TOKEN_MISSING",
			"value" => "15",
			"category" => "ERROR",
		],
		"ERROR_CODE_UNAUTHORIZED_FORM_SUBMISSION" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_16",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_16.php",
			"constant" => "ERROR_CODE_UNAUTHORIZED_FORM_SUBMISSION",
			"value" => "16",
			"category" => "ERROR",
		],
		"ERROR_CODE_INTERNAL_ERROR" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_17",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_17.php",
			"constant" => "ERROR_CODE_INTERNAL_ERROR",
			"value" => "17",
			"category" => "ERROR",
		],
		"ERROR_CODE_LOGIN_ERROR" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_18",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_18.php",
			"constant" => "ERROR_CODE_LOGIN_ERROR",
			"value" => "18",
			"category" => "ERROR",
		],
		"ERROR_CODE_PENDING_VERIFICATION" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_19",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_19.php",
			"constant" => "ERROR_CODE_PENDING_VERIFICATION",
			"value" => "19",
			"category" => "ERROR",
		],
		"ERROR_CODE_LOGIN_INVALID_DETAILS" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_2",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_2.php",
			"constant" => "ERROR_CODE_LOGIN_INVALID_DETAILS",
			"value" => "2",
			"category" => "ERROR",
		],
		"ERROR_CODE_SUCCESS_REGISTER" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_20",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_20.php",
			"constant" => "ERROR_CODE_SUCCESS_REGISTER",
			"value" => "20",
			"category" => "ERROR",
		],
		"ERROR_CODE_ACCOUNT_UPDATED" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_21",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_21.php",
			"constant" => "ERROR_CODE_ACCOUNT_UPDATED",
			"value" => "21",
			"category" => "ERROR",
		],
		"ERROR_CODE_FORGOT_PASSWORD" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_3",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_3.php",
			"constant" => "ERROR_CODE_FORGOT_PASSWORD",
			"value" => "3",
			"category" => "ERROR",
		],
		"ERROR_CODE_DB_ERROR" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_4",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_4.php",
			"constant" => "ERROR_CODE_DB_ERROR",
			"value" => "4",
			"category" => "ERROR",
		],
		"ERROR_CODE_404" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_404",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_404.php",
			"constant" => "ERROR_CODE_404",
			"value" => "404",
			"category" => "ERROR",
		],
		"ERROR_CODE_NOT_LOGGED_IN" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_5",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_5.php",
			"constant" => "ERROR_CODE_NOT_LOGGED_IN",
			"value" => "5",
			"category" => "ERROR",
		],
		"ERROR_CODE_500" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_500",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_500.php",
			"constant" => "ERROR_CODE_500",
			"value" => "500",
			"category" => "ERROR",
		],
		"ERROR_CODE_ACTIVE_SESSION" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_6",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_6.php",
			"constant" => "ERROR_CODE_ACTIVE_SESSION",
			"value" => "6",
			"category" => "ERROR",
		],
		"ERROR_CODE_REQUEST_ERROR" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_7",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_7.php",
			"constant" => "ERROR_CODE_REQUEST_ERROR",
			"value" => "7",
			"category" => "ERROR",
		],
		"ERROR_CODE_RECOVERY_PASSWORD" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_8",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_8.php",
			"constant" => "ERROR_CODE_RECOVERY_PASSWORD",
			"value" => "8",
			"category" => "ERROR",
		],
		"ERROR_CODE_MAINTENANCE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\error\\error_code_9",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/error/error_code_9.php",
			"constant" => "ERROR_CODE_MAINTENANCE",
			"value" => "9",
			"category" => "ERROR",
		],
		"MESSAGE_CODE_100" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\message\\message_code_100",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/message/message_code_100.php",
			"constant" => "MESSAGE_CODE_100",
			"value" => "100",
			"category" => "MESSAGE",
		],
		"MESSAGE_CODE_101" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\message\\message_code_101",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/message/message_code_101.php",
			"constant" => "MESSAGE_CODE_101",
			"value" => "101",
			"category" => "MESSAGE",
		],
		"MESSAGE_CODE_102" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\message\\message_code_102",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/message/message_code_102.php",
			"constant" => "MESSAGE_CODE_102",
			"value" => "102",
			"category" => "MESSAGE",
		],
		"PRODUCT_PROPERTY_COLOR_DESCRIPTION" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\color_description",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/color_description.php",
			"constant" => "PRODUCT_PROPERTY_COLOR_DESCRIPTION",
			"value" => "gs1.product:ColourDescription",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_COST_PRICE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\cost_price",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/cost_price.php",
			"constant" => "PRODUCT_PROPERTY_COST_PRICE",
			"value" => "gs1.price:PriceSpecification:CostPrice",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_DEPTH" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\depth",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/depth.php",
			"constant" => "PRODUCT_PROPERTY_DEPTH",
			"value" => "gs1.product:depth:outOfPackageDepth",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_DIMENSIONS" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\dimensions",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/dimensions.php",
			"constant" => "PRODUCT_PROPERTY_DIMENSIONS",
			"value" => "gs1.product:Dimensions",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_DISCOUNT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\discount",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/discount.php",
			"constant" => "PRODUCT_PROPERTY_DISCOUNT",
			"value" => "urn:gs1:gdd:cl:AllowanceChargeTypeCode:DI",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PRICE_DISCOUNTED" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\discounted_price",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/discounted_price.php",
			"constant" => "PRODUCT_PROPERTY_PRICE_DISCOUNTED",
			"value" => "gs1.product.cost:DISCOUNTED_PRICE",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_EXTERNAL_LINK" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\external_link",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/external_link.php",
			"constant" => "PRODUCT_PROPERTY_EXTERNAL_LINK",
			"value" => "gs1.product:EXTERNAL_LINK",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_FEATURE_COLOR" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\feature_color",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/feature_color.php",
			"constant" => "PRODUCT_PROPERTY_FEATURE_COLOR",
			"value" => "gs1.product:FEATURE:COLOR",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_FILTER_COLOR" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\filter_color",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/filter_color.php",
			"constant" => "PRODUCT_PROPERTY_FILTER_COLOR",
			"value" => "gs1.product.filter:ColourDescription",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_FILTER_MATERIAL" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\filter_material",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/filter_material.php",
			"constant" => "PRODUCT_PROPERTY_FILTER_MATERIAL",
			"value" => "gs1.product.filter:material",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_HEIGHT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\height",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/height.php",
			"constant" => "PRODUCT_PROPERTY_HEIGHT",
			"value" => "gs1.product:height:outOfPackageHeight",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_IS_FEATURED" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\is_featured",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/is_featured.php",
			"constant" => "PRODUCT_PROPERTY_IS_FEATURED",
			"value" => "gs1.product:IS_FEATURED",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_IS_PARENT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\is_parent",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/is_parent.php",
			"constant" => "PRODUCT_PROPERTY_IS_PARENT",
			"value" => "gs1.product:IS_PARENT",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_KEYWORD" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\keyword",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/keyword.php",
			"constant" => "PRODUCT_PROPERTY_KEYWORD",
			"value" => "gs1:AdditionalProductClassificationDetails",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_LAST_UPDATED" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\last_updated",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/last_updated.php",
			"constant" => "PRODUCT_PROPERTY_LAST_UPDATED",
			"value" => "gs1.product:additionalProperty:dateLastUpdated",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_LEAD_TIME" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\lead_time",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/lead_time.php",
			"constant" => "PRODUCT_PROPERTY_LEAD_TIME",
			"value" => "gs1.product:lead_time",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_MATERIAL" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\material",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/material.php",
			"constant" => "PRODUCT_PROPERTY_MATERIAL",
			"value" => "gs1.product:material",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_METAL_TYPE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\metal_type",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/metal_type.php",
			"constant" => "PRODUCT_PROPERTY_METAL_TYPE",
			"value" => "gs1.product:metal_type",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_NUMBER_OF_UNITS" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\number_of_units",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/number_of_units.php",
			"constant" => "PRODUCT_PROPERTY_NUMBER_OF_UNITS",
			"value" => "gs1.product:NUMBER_OF_UNITS",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PACKAGE_DEPTH" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\package_depth",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/package_depth.php",
			"constant" => "PRODUCT_PROPERTY_PACKAGE_DEPTH",
			"value" => "gs1.product.package:depth",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PACKAGE_HEIGHT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\package_height",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/package_height.php",
			"constant" => "PRODUCT_PROPERTY_PACKAGE_HEIGHT",
			"value" => "gs1.product.package:height",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PACKAGE_SIZE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\package_size",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/package_size.php",
			"constant" => "PRODUCT_PROPERTY_PACKAGE_SIZE",
			"value" => "gs1:package_size",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PACKAGE_WEIGHT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\package_weight",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/package_weight.php",
			"constant" => "PRODUCT_PROPERTY_PACKAGE_WEIGHT",
			"value" => "gs1.product.package:weight",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PACKAGE_WIDTH" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\package_width",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/package_width.php",
			"constant" => "PRODUCT_PROPERTY_PACKAGE_WIDTH",
			"value" => "gs1.product.package:width",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PARENT_KEY" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\parent_key",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/parent_key.php",
			"constant" => "PRODUCT_PROPERTY_PARENT_KEY",
			"value" => "gs1.product.parent:PRODUCT_KEY",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PRICE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\price",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/price.php",
			"constant" => "PRODUCT_PROPERTY_PRICE",
			"value" => "urn:gs1:gdd:cl:AllowanceChargeTypeCode:CP",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PROMOTION_DATE_FROM" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\promotion_date_from",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/promotion_date_from.php",
			"constant" => "PRODUCT_PROPERTY_PROMOTION_DATE_FROM",
			"value" => "gs1.product.promotion:DATE_FROM",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PROMOTION_DATE_TO" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\promotion_date_to",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/promotion_date_to.php",
			"constant" => "PRODUCT_PROPERTY_PROMOTION_DATE_TO",
			"value" => "gs1.product.promotion:DATE_TO",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PROMOTION_IS_CLEARANCE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\promotion_is_clearance",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/promotion_is_clearance.php",
			"constant" => "PRODUCT_PROPERTY_PROMOTION_IS_CLEARANCE",
			"value" => "gs1.product.promotion:IS_CLEARANCE",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PROMOTION_PRICE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\promotion_price",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/promotion_price.php",
			"constant" => "PRODUCT_PROPERTY_PROMOTION_PRICE",
			"value" => "gs1.product.promotion:PRICE",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PRO_DESCRIPTION" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\pro_description",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/pro_description.php",
			"constant" => "PRODUCT_PROPERTY_PRO_DESCRIPTION",
			"value" => "gs1.product:productDescription",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_DEVELOPMENT_NAME" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\pro_development_name",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/pro_development_name.php",
			"constant" => "PRODUCT_PROPERTY_DEVELOPMENT_NAME",
			"value" => "gs1.product:DEVELOPMENT_NAME",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PRO_IS_INACTIVE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\pro_is_inactive",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/pro_is_inactive.php",
			"constant" => "PRODUCT_PROPERTY_PRO_IS_INACTIVE",
			"value" => "product:StateInSystem:IS_INACTIVE",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PRO_IS_PUBLISHED" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\pro_is_published",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/pro_is_published.php",
			"constant" => "PRODUCT_PROPERTY_PRO_IS_PUBLISHED",
			"value" => "product:StateInSystem:IS_PUBLISHED",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PRO_LENGTH" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\pro_length",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/pro_length.php",
			"constant" => "PRODUCT_PROPERTY_PRO_LENGTH",
			"value" => "gs1.product:length",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PRO_LONG_DESCRIPTION" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\pro_long_description",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/pro_long_description.php",
			"constant" => "PRODUCT_PROPERTY_PRO_LONG_DESCRIPTION",
			"value" => "gs1.product:productDescription:LONG",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PRO_META_DESCRIPTION" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\pro_meta_description",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/pro_meta_description.php",
			"constant" => "PRODUCT_PROPERTY_PRO_META_DESCRIPTION",
			"value" => "gs1.product:productDescription:META",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PRO_NAME" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\pro_name",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/pro_name.php",
			"constant" => "PRODUCT_PROPERTY_PRO_NAME",
			"value" => "gs1.product:productName",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_SEO_CODE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\pro_seo_name",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/pro_seo_name.php",
			"constant" => "PRODUCT_PROPERTY_SEO_CODE",
			"value" => "gs1.product:seo_code",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_PRO_SHORT_DESCRIPTION" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\pro_short_description",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/pro_short_description.php",
			"constant" => "PRODUCT_PROPERTY_PRO_SHORT_DESCRIPTION",
			"value" => "gs1.product:productDescription:SHORT",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_RATING" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\rating",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/rating.php",
			"constant" => "PRODUCT_PROPERTY_RATING",
			"value" => "gs1:AdditionalProductStarRating",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_SALES_PRICE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\sales_price",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/sales_price.php",
			"constant" => "PRODUCT_PROPERTY_SALES_PRICE",
			"value" => "gs1.product:SALES_PRICE",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_SECURITY_STATE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\security_state",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/security_state.php",
			"constant" => "PRODUCT_PROPERTY_SECURITY_STATE",
			"value" => "urn:gs1:gdd:cl:productSecureState",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_SIZE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\size",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/size.php",
			"constant" => "PRODUCT_PROPERTY_SIZE",
			"value" => "gs1.product:SIZE",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_SIZE_TYPE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\size_type",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/size_type.php",
			"constant" => "PRODUCT_PROPERTY_SIZE_TYPE",
			"value" => "gs1.product:descriptiveSize",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_STOCK" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\stock",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/stock.php",
			"constant" => "PRODUCT_PROPERTY_STOCK",
			"value" => "urn:gs1:gdd:cl:TransactionalReferenceTypeCode:GRN",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_STOCK_ON_HAND" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\stock_on_hand",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/stock_on_hand.php",
			"constant" => "PRODUCT_PROPERTY_STOCK_ON_HAND",
			"value" => "urn:gs1:gdd:cl:TransactionalReferenceTypeCode:GRNonHand",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_TERMS_AND_CONDITIONS" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\terms_and_conditions",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/terms_and_conditions.php",
			"constant" => "PRODUCT_PROPERTY_TERMS_AND_CONDITIONS",
			"value" => "gs1.product:terms_and_conditions",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_THRESHOLD" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\threshold",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/threshold.php",
			"constant" => "PRODUCT_PROPERTY_THRESHOLD",
			"value" => "gs1.product:threshold:generic",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_UNIT_OF_MEASURE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\unit_of_measure",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/unit_of_measure.php",
			"constant" => "PRODUCT_PROPERTY_UNIT_OF_MEASURE",
			"value" => "urn:gs1:gdd:cl:FunctionalBasisUnitCode",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_VOLUME" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\volume",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/volume.php",
			"constant" => "PRODUCT_PROPERTY_VOLUME",
			"value" => "gs1.product:volume",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_WEIGHT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\weight",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/weight.php",
			"constant" => "PRODUCT_PROPERTY_WEIGHT",
			"value" => "gs1.product:weight:netWeight",
			"category" => "PRODUCT_PROPERTY",
		],
		"PRODUCT_PROPERTY_WIDTH" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\product_property\\width",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/product_property/width.php",
			"constant" => "PRODUCT_PROPERTY_WIDTH",
			"value" => "gs1.product:width:outOfPackageWidth",
			"category" => "PRODUCT_PROPERTY",
		],
		"SETTING_APP_CURRENCY_REMOVE_DECIMALS" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\app_currency_remove_decimals",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/app_currency_remove_decimals.php",
			"constant" => "SETTING_APP_CURRENCY_REMOVE_DECIMALS",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_APP_CURRENCY_VAT_AMOUNT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\app_currency_vat_amount",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/app_currency_vat_amount.php",
			"constant" => "SETTING_APP_CURRENCY_VAT_AMOUNT",
			"value" => "15",
			"category" => "SETTINGS",
		],
		"SETTING_BS_DANGER" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\bs_danger",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/bs_danger.php",
			"constant" => "SETTING_BS_DANGER",
			"value" => "#dc3f35",
			"category" => "SETTINGS",
		],
		"SETTING_BS_DARK" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\bs_dark",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/bs_dark.php",
			"constant" => "SETTING_BS_DARK",
			"value" => "#212529",
			"category" => "SETTINGS",
		],
		"SETTING_BS_INFO" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\bs_info",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/bs_info.php",
			"constant" => "SETTING_BS_INFO",
			"value" => "#0dcaf0",
			"category" => "SETTINGS",
		],
		"SETTING_BS_LIGHT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\bs_light",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/bs_light.php",
			"constant" => "SETTING_BS_LIGHT",
			"value" => "#EBEDEC",
			"category" => "SETTINGS",
		],
		"SETTING_BS_PRIMARY" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\bs_primary",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/bs_primary.php",
			"constant" => "SETTING_BS_PRIMARY",
			"value" => "#6a90ca",
			"category" => "SETTINGS",
		],
		"SETTING_BS_SECONDARY" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\bs_secondary",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/bs_secondary.php",
			"constant" => "SETTING_BS_SECONDARY",
			"value" => "#435A7E",
			"category" => "SETTINGS",
		],
		"SETTING_BS_SUCCESS" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\bs_success",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/bs_success.php",
			"constant" => "SETTING_BS_SUCCESS",
			"value" => "#198754",
			"category" => "SETTINGS",
		],
		"SETTING_BS_VARIABLES_BACKUP" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\bs_variables_backup",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/bs_variables_backup.php",
			"constant" => "SETTING_BS_VARIABLES_BACKUP",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_BS_WARNING" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\bs_warning",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/bs_warning.php",
			"constant" => "SETTING_BS_WARNING",
			"value" => "#ffc107",
			"category" => "SETTINGS",
		],
		"SETTING_CALL_TO_ACTION_BUTTON_LINK" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\call_to_action_button_link",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/call_to_action_button_link.php",
			"constant" => "SETTING_CALL_TO_ACTION_BUTTON_LINK",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_CALL_TO_ACTION_BUTTON_TEXT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\call_to_action_button_text",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/call_to_action_button_text.php",
			"constant" => "SETTING_CALL_TO_ACTION_BUTTON_TEXT",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_CALL_TO_ACTION_DESCRIPTION" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\call_to_action_description",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/call_to_action_description.php",
			"constant" => "SETTING_CALL_TO_ACTION_DESCRIPTION",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_CALL_TO_ACTION_HEADING" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\call_to_action_heading",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/call_to_action_heading.php",
			"constant" => "SETTING_CALL_TO_ACTION_HEADING",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_CALL_TO_ACTION_IMAGE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\call_to_action_image",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/call_to_action_image.php",
			"constant" => "SETTING_CALL_TO_ACTION_IMAGE",
			"value" => "null",
			"category" => "SETTINGS",
		],
		"SETTING_CALL_TO_ACTION_YOUTUBE_LINK" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\call_to_action_youtube_link",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/call_to_action_youtube_link.php",
			"constant" => "SETTING_CALL_TO_ACTION_YOUTUBE_LINK",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_ABOUT_US" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_about_us",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_about_us.php",
			"constant" => "SETTING_COMPANY_ABOUT_US",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_ABOUT_US_IMAGE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_about_us_image",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_about_us_image.php",
			"constant" => "SETTING_COMPANY_ABOUT_US_IMAGE",
			"value" => "null",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_ABOUT_YOUTUBE_EMBED_CODE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_about_youtube_embed_code",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_about_youtube_embed_code.php",
			"constant" => "SETTING_COMPANY_ABOUT_YOUTUBE_EMBED_CODE",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_ABOUT_US_YOUTUBE_LINK" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_about_youtube_link",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_about_youtube_link.php",
			"constant" => "SETTING_COMPANY_ABOUT_US_YOUTUBE_LINK",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_COMPANY_ADDRESS_REF" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_address_ref",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_address_ref.php",
			"constant" => "SETTING_COMPANY_COMPANY_ADDRESS_REF",
			"value" => "null",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_COPYRIGHT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_copyright",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_copyright.php",
			"constant" => "SETTING_COMPANY_COPYRIGHT",
			"value" => "© Patriot RSA %s. Copyright",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_EMAIL" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_email",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_email.php",
			"constant" => "SETTING_COMPANY_EMAIL",
			"value" => "admin@patriotapparel.co.za",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_EMAIL_ACCOUNTS" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_email_accounts",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_email_accounts.php",
			"constant" => "SETTING_COMPANY_EMAIL_ACCOUNTS",
			"value" => "admin@patriotapparel.co.za",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_EMAIL_ADMIN" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_email_admin",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_email_admin.php",
			"constant" => "SETTING_COMPANY_EMAIL_ADMIN",
			"value" => "admin@patriotapparel.co.za",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_EMAIL_APPOINTMENT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_email_appointment",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_email_appointment.php",
			"constant" => "SETTING_COMPANY_EMAIL_APPOINTMENT",
			"value" => "admin@patriotapparel.co.za",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_EMAIL_CONTACT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_email_contact",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_email_contact.php",
			"constant" => "SETTING_COMPANY_EMAIL_CONTACT",
			"value" => "admin@patriotapparel.co.za",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_EMAIL_FROM" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_email_from",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_email_from.php",
			"constant" => "SETTING_COMPANY_EMAIL_FROM",
			"value" => "admin@patriotapparel.co.za",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_EMAIL_NO_REPLY" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_email_no_reply",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_email_no_reply.php",
			"constant" => "SETTING_COMPANY_EMAIL_NO_REPLY",
			"value" => "admin@patriotapparel.co.za",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_EMAIL_ORDER" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_email_order",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_email_order.php",
			"constant" => "SETTING_COMPANY_EMAIL_ORDER",
			"value" => "admin@patriotapparel.co.za",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_EMAIL_REPAIRS" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_email_repairs",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_email_repairs.php",
			"constant" => "SETTING_COMPANY_EMAIL_REPAIRS",
			"value" => "admin@patriotapparel.co.za",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_EMAIL_SALES" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_email_sales",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_email_sales.php",
			"constant" => "SETTING_COMPANY_EMAIL_SALES",
			"value" => "admin@patriotapparel.co.za",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_EMAIL_SUPPORT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_email_support",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_email_support.php",
			"constant" => "SETTING_COMPANY_EMAIL_SUPPORT",
			"value" => "admin@patriotapparel.co.za",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_EMAIL_TEST_CC" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_email_test_cc",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_email_test_cc.php",
			"constant" => "SETTING_COMPANY_EMAIL_TEST_CC",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_COMPANY_FAVICON_REF" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_favicon_ref",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_favicon_ref.php",
			"constant" => "SETTING_COMPANY_COMPANY_FAVICON_REF",
			"value" => "null",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_JOIN_OUR_TEAM" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_join_our_team",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_join_our_team.php",
			"constant" => "SETTING_COMPANY_JOIN_OUR_TEAM",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_JOIN_OUR_TEAM_IMAGE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_join_our_team_image",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_join_our_team_image.php",
			"constant" => "SETTING_COMPANY_JOIN_OUR_TEAM_IMAGE",
			"value" => "null",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_JOIN_OUR_TEAM_YOUTUBE_LINK" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_join_our_team_youtube_link",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_join_our_team_youtube_link.php",
			"constant" => "SETTING_COMPANY_JOIN_OUR_TEAM_YOUTUBE_LINK",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_COMPANY_LOGO_DARK_REF" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_logo_dark_ref",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_logo_dark_ref.php",
			"constant" => "SETTING_COMPANY_COMPANY_LOGO_DARK_REF",
			"value" => "null",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_COMPANY_LOGO_LIGHT_REF" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_logo_light_ref",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_logo_light_ref.php",
			"constant" => "SETTING_COMPANY_COMPANY_LOGO_LIGHT_REF",
			"value" => "null",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_MAP_CODE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_map_code",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_map_code.php",
			"constant" => "SETTING_COMPANY_MAP_CODE",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_NAME" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_name",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_name.php",
			"constant" => "SETTING_COMPANY_NAME",
			"value" => "PatriotRSA Ontwerpe",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_NOTES" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_notes",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_notes.php",
			"constant" => "SETTING_COMPANY_NOTES",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_PREFIX" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_prefix",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_prefix.php",
			"constant" => "SETTING_COMPANY_PREFIX",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_REG_NO" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_reg_no",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_reg_no.php",
			"constant" => "SETTING_COMPANY_REG_NO",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_SERVICES_ASSET_MANAGEMENT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_services_asset_management",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_services_asset_management.php",
			"constant" => "SETTING_COMPANY_SERVICES_ASSET_MANAGEMENT",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_SERVICES_ASSET_MANAGEMENT_IMAGE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_services_asset_management_image",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_services_asset_management_image.php",
			"constant" => "SETTING_COMPANY_SERVICES_ASSET_MANAGEMENT_IMAGE",
			"value" => "null",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_SERVICES_ASSET_MANAGEMENT_YOUTUBE_LINK" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_services_asset_management_youtube_link",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_services_asset_management_youtube_link.php",
			"constant" => "SETTING_COMPANY_SERVICES_ASSET_MANAGEMENT_YOUTUBE_LINK",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_SERVICES_AUCTIONS" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_services_auctions",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_services_auctions.php",
			"constant" => "SETTING_COMPANY_SERVICES_AUCTIONS",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_SERVICES_AUCTIONS_IMAGE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_services_auctions_image",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_services_auctions_image.php",
			"constant" => "SETTING_COMPANY_SERVICES_AUCTIONS_IMAGE",
			"value" => "null",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_SERVICES_AUCTIONS_YOUTUBE_LINK" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_services_auctions_youtube_link",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_services_auctions_youtube_link.php",
			"constant" => "SETTING_COMPANY_SERVICES_AUCTIONS_YOUTUBE_LINK",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_SERVICES_DEVELOPMENTS" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_services_developments",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_services_developments.php",
			"constant" => "SETTING_COMPANY_SERVICES_DEVELOPMENTS",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_SERVICES_DEVELOPMENTS_IMAGE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_services_developments_image",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_services_developments_image.php",
			"constant" => "SETTING_COMPANY_SERVICES_DEVELOPMENTS_IMAGE",
			"value" => "null",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_SERVICES_DEVELOPMENTS_YOUTUBE_LINK" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_services_developments_youtube_link",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_services_developments_youtube_link.php",
			"constant" => "SETTING_COMPANY_SERVICES_DEVELOPMENTS_YOUTUBE_LINK",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_SERVICES_SELLING" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_services_selling",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_services_selling.php",
			"constant" => "SETTING_COMPANY_SERVICES_SELLING",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_SERVICES_SELLING_IMAGE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_services_selling_image",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_services_selling_image.php",
			"constant" => "SETTING_COMPANY_SERVICES_SELLING_IMAGE",
			"value" => "null",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_SERVICES_SELLING_YOUTUBE_LINK" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_services_selling_youtube_link",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_services_selling_youtube_link.php",
			"constant" => "SETTING_COMPANY_SERVICES_SELLING_YOUTUBE_LINK",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_SERVICES_VALUATIONS" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_services_valuations",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_services_valuations.php",
			"constant" => "SETTING_COMPANY_SERVICES_VALUATIONS",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_SERVICES_VALUATIONS_IMAGE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_services_valuations_image",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_services_valuations_image.php",
			"constant" => "SETTING_COMPANY_SERVICES_VALUATIONS_IMAGE",
			"value" => "null",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_SERVICES_VALUATIONS_YOUTUBE_LINK" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_services_valuations_youtube_link",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_services_valuations_youtube_link.php",
			"constant" => "SETTING_COMPANY_SERVICES_VALUATIONS_YOUTUBE_LINK",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_TELLNR_CONTACT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_tellnr_contact",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_tellnr_contact.php",
			"constant" => "SETTING_COMPANY_TELLNR_CONTACT",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_TELLNR_FAX" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_tellnr_fax",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_tellnr_fax.php",
			"constant" => "SETTING_COMPANY_TELLNR_FAX",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_TELLNR_GENERAL" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_tellnr_general",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_tellnr_general.php",
			"constant" => "SETTING_COMPANY_TELLNR_GENERAL",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_TELLNR_OFFICE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_tellnr_office",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_tellnr_office.php",
			"constant" => "SETTING_COMPANY_TELLNR_OFFICE",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_TELLNR_SALES" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_tellnr_sales",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_tellnr_sales.php",
			"constant" => "SETTING_COMPANY_TELLNR_SALES",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_TELLNR_WORK" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_tellnr_work",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_tellnr_work.php",
			"constant" => "SETTING_COMPANY_TELLNR_WORK",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_VALUE_ADDED_SERVICES" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_value_added_services",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_value_added_services.php",
			"constant" => "SETTING_COMPANY_VALUE_ADDED_SERVICES",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_VALUE_ADDED_SERVICES_IMAGE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_value_added_services_image",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_value_added_services_image.php",
			"constant" => "SETTING_COMPANY_VALUE_ADDED_SERVICES_IMAGE",
			"value" => "null",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_VALUE_ADDED_SERVICES_YOUTUBE_LINK" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_value_added_services_youtube_link",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_value_added_services_youtube_link.php",
			"constant" => "SETTING_COMPANY_VALUE_ADDED_SERVICES_YOUTUBE_LINK",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_VAT_NO" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_vat_no",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_vat_no.php",
			"constant" => "SETTING_COMPANY_VAT_NO",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_WEBSITE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\company_website",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/company_website.php",
			"constant" => "SETTING_COMPANY_WEBSITE",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_COMPANY_EMAIL_DISCLAIMER" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\email_disclaimer",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/email_disclaimer.php",
			"constant" => "SETTING_COMPANY_EMAIL_DISCLAIMER",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_ENABLE_CART" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\enable_cart",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/enable_cart.php",
			"constant" => "SETTING_ENABLE_CART",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_EXTERNAL_PUBLISHING_PLATFORM_ENABLE_GUMTREE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\external_publishing_platform_enable_gumtree",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/external_publishing_platform_enable_gumtree.php",
			"constant" => "SETTING_EXTERNAL_PUBLISHING_PLATFORM_ENABLE_GUMTREE",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_EXTERNAL_PUBLISHING_PLATFORM_ENABLE_PRIVATE_PROPERTY" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\external_publishing_platform_enable_private_property",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/external_publishing_platform_enable_private_property.php",
			"constant" => "SETTING_EXTERNAL_PUBLISHING_PLATFORM_ENABLE_PRIVATE_PROPERTY",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_EXTERNAL_PUBLISHING_PLATFORM_GUMTREE" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\external_publishing_platform_gumtree",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/external_publishing_platform_gumtree.php",
			"constant" => "SETTING_EXTERNAL_PUBLISHING_PLATFORM_GUMTREE",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_EXTERNAL_PUBLISHING_PLATFORM_PRIVATE_PROPERTY" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\external_publishing_platform_private_property",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/external_publishing_platform_private_property.php",
			"constant" => "SETTING_EXTERNAL_PUBLISHING_PLATFORM_PRIVATE_PROPERTY",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_MAILCHIMP_API_KEY" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\mailchimp_api_key",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/mailchimp_api_key.php",
			"constant" => "SETTING_MAILCHIMP_API_KEY",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_MAILCHIMP_AUDIENCE_ID" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\mailchimp_audience_id",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/mailchimp_audience_id.php",
			"constant" => "SETTING_MAILCHIMP_AUDIENCE_ID",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_MAILCHIMP_SERVER_PREFIX" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\mailchimp_server_prefix",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/mailchimp_server_prefix.php",
			"constant" => "SETTING_MAILCHIMP_SERVER_PREFIX",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_OCTOAPI_SERVICE_PASSWORD" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\octoapi_service_password",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/octoapi_service_password.php",
			"constant" => "SETTING_OCTOAPI_SERVICE_PASSWORD",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_OCTOAPI_SERVICE_URL" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\octoapi_service_url",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/octoapi_service_url.php",
			"constant" => "SETTING_OCTOAPI_SERVICE_URL",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_OCTOAPI_SERVICE_USERNAME" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\octoapi_service_username",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/octoapi_service_username.php",
			"constant" => "SETTING_OCTOAPI_SERVICE_USERNAME",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_ORDER_PREFIX" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\order_prefix",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/order_prefix.php",
			"constant" => "SETTING_ORDER_PREFIX",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_POLICY_PRIVACY" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\policy_privacy",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/policy_privacy.php",
			"constant" => "SETTING_POLICY_PRIVACY",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_POLICY_RETURNS" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\policy_returns",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/policy_returns.php",
			"constant" => "SETTING_POLICY_RETURNS",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_POLICY_SHIPPING" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\policy_shipping",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/policy_shipping.php",
			"constant" => "SETTING_POLICY_SHIPPING",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_PROMOTION_VOUCHER_PREFIX" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\promotion_voucher_prefix",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/promotion_voucher_prefix.php",
			"constant" => "SETTING_PROMOTION_VOUCHER_PREFIX",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_RESERVE_OVERRIDE_END_TIME" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\reserve_override_end_time",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/reserve_override_end_time.php",
			"constant" => "SETTING_RESERVE_OVERRIDE_END_TIME",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_RESERVE_OVERRIDE_START_TIME" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\reserve_override_start_time",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/reserve_override_start_time.php",
			"constant" => "SETTING_RESERVE_OVERRIDE_START_TIME",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_SHARING_TERMS_AND_CONDITIONS" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\sharing_terms_and_conditions",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/sharing_terms_and_conditions.php",
			"constant" => "SETTING_SHARING_TERMS_AND_CONDITIONS",
			"value" => "",
			"category" => "SETTINGS",
		],
		"SETTING_TERMS_AND_CONDITIONS" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\settings\\terms_and_conditions",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/settings/terms_and_conditions.php",
			"constant" => "SETTING_TERMS_AND_CONDITIONS",
			"value" => "",
			"category" => "SETTINGS",
		],
		"USER_ROLE_ADMIN" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\user_role\\admin",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/user_role/admin.php",
			"constant" => "USER_ROLE_ADMIN",
			"value" => "ADMIN",
			"category" => "USER_ROLE",
		],
		"USER_ROLE_CLIENT" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\user_role\\client",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/user_role/client.php",
			"constant" => "USER_ROLE_CLIENT",
			"value" => "CLIENT",
			"category" => "USER_ROLE",
		],
		"USER_ROLE_DEV" => [
			"classname" => "\\Kwerqy\\Ember\\com\\solid_classes\\user_role\\dev",
			"filename" => "C:\inetpub\wwwroot\diepatriot\project-root\vendor\kwerqy\ember\src\com\incl/../../com/solid_classes/user_role/dev.php",
			"constant" => "USER_ROLE_DEV",
			"value" => "DEV",
			"category" => "USER_ROLE",
		],
	];

}

